### ISSUE TITLE
branding of new live grub-theme

### ISSUE THREAD

**Issue by udeved** [manjaro/release-plan#125] opened 2017-03-25 16:15 UTC
We need to brand [grub-theme](https://github.com/manjaro/grub-theme/tree/master/manjaro-live) for the live media, manjarofy it.
Grub will be implemented in buildiso starting with 0.15.1 to be released this weekend.

I currently removed all branding.

**Comment by philmmanjaro** [comment] 2017-03-25 16:48
Might be easier to announce it also in our forums so people can commit to it ...

**Comment by Ste74** [comment] 2017-03-25 16:56
I agree , help of our users is always appreciated ..

**Comment by udeved** [comment] 2017-03-25 17:59
Could someone write a nice text? 
It perhaps requires a bit more flowery language I not so good with.

**Comment by udeved** [comment] 2017-03-25 18:14
@philmmanjaro 

Do we want to do a 17.0.1 release?
 We would have grub on iso, and all the mesa and driver stuff solved new downloaders encounter with 17.0

**Comment by Ste74** [comment] 2017-03-25 18:32
I can try to announce .. i want ask also a new set of icons...

**Comment by udeved** [comment] 2017-03-25 18:34
@Ste74 

I had the idea to take the breath icons. But new icons are also welcome. ;)

**Comment by philmmanjaro** [comment] 2017-03-25 18:44
Yes, we plan **v17.0.1** to be released soon. However we have to check if **catalyst** is now broken and can be removed aswell.

**Comment by Ste74** [comment] 2017-03-25 18:44
Now i have to go out whit my family , tomorrow or tonight  will write it 😉

**Comment by udeved** [comment] 2017-03-25 18:47
Enjoy the time @Ste74 

We probably also need logo/motto in svg, so we can package these, but not tonight. 😆

**Comment by philmmanjaro** [comment] 2017-03-27 17:17
I miss the **nonfree** option within the new **grub-menu**. How do we handle that feature now?

**Comment by udeved** [comment] 2017-03-27 17:21
Good question, the kernel args are not per kernel any longer. It works differently on grub.

**Comment by udeved** [comment] 2017-03-27 17:24
My proposal, we drop nonfree drivers from iso, drop the video_args also.

    nonfree=true nouveau.modeset=1 i915.modeset=1 radeon.modeset=1

And we add in CAL mhwdcfg a widget to select free/nonfree.
Do we really need nonfree drivers on iso?

**Comment by philmmanjaro** [comment] 2017-03-27 17:24
I see **nonfree=true** set by default. We have to create an option as we do with **lang** and such.

**Comment by philmmanjaro** [comment] 2017-03-27 17:25
Yes, we need **nonfree** on ISO to test the drivers. Please make it adjustable. If we had an option to choose proprietary drivers we either set the needed parameters or not. And we can use a gfx icon or so.

**Comment by udeved** [comment] 2017-03-27 17:30
You build iso to test drivers?

I usually test on real hardware and a build, no iso.
Whats the plus with iso?

**Comment by philmmanjaro** [comment] 2017-03-27 17:33
To give the drivers a try if they work on your hardware or not. Simple as that. See what you get. Please add an option for **nonfree** drivers as it is possible and we won't provide less options as we had with previous option **isolinux**. Thx.

**Comment by udeved** [comment] 2017-03-27 17:41
Just saying, if its for the sake of testing drivers, and we can overall improve hardware coverage by dropping nonfree drivers, because the default args may clash with free drivers on some hardware, why not have a test-drivers-on-iso script based on mkgrub-rescue?

**Comment by philmmanjaro** [comment] 2017-03-27 17:44
Simply add an option to select if **proprietary drivers** should be used or not. We had it all the time and it worked as it worked. People will test if all functions are working with those drivers. That is one of our key features. If we remove it we won't have it. Simply don't argue with me on this one. If you have not the time to do it I'll do it. Simple put we will re-add this feature. Hope this is now clear.

**Comment by udeved** [comment] 2017-03-27 17:45
Evil me heretic.

I see what I can do your majesty.

**Comment by philmmanjaro** [comment] 2017-03-27 17:50
I suggest to make it optional. So we can drop that function if needed. Grub has nice features for creating submenus. Simple source it. It is good to have two options. Enable and disable **proprietary drivers**. By default please disable it as we do with the **isolinux** boot menu. It is really a plus to have that option. If not added the **bumblebee** hybrid function doesn't work for example. 

Sure we can add a widget to **Calamares** some time and consider to drop it if needed. For now it is one of our features I like to keep. I tested it so far. Works as it should. Currently some people might wonder why only **Nvidia** gets loaded and not **Nouveau** :smile:

**Comment by udeved** [comment] 2017-03-27 17:53
You may not realize it yet, grub scripting requires some read.
Its similar to bash, but not quite, useful to know what grub module prides what.

**Comment by philmmanjaro** [comment] 2017-03-27 18:23
We had two options: 

* free drivers: nouveau.modeset=1 i915.modeset=1 radeon.modeset=1
* nonfree drivers: nouveau.modeset=0 i915.modeset=1 radeon.modeset=0 nonfree=yes

If we still need those modesets we have to check. Let me try to write a config for it.

**Comment by udeved** [comment] 2017-03-27 18:45
We set them temporarily in buildiso code. Its easier for the moment.

**Comment by philmmanjaro** [comment] 2017-03-27 18:48
Hmm, ok. Seems you found a way to make an option. In the mean time I wrote also some, however yours seems to be be more efficient :smile: 

```
function nonfree_mhwd {
  menuentry --class=mhwd.$class --hotkey=d "driver=${def_driver}" {# set driver above with the editor
  default=0
  submenu --class=mhwd.free "Use free drivers" {
   def_driver="nouveau.modeset=1 i915.modeset=1 radeon.modeset=1"
  }
  submenu --class=mhwd.nonfree "Use proprietary drivers" {
   def_driver="nouveau.modeset=0 i915.modeset=1 radeon.modeset=0 nonfree=yes"
  }
  menu_reload
}
```

**Comment by udeved** [comment] 2017-03-27 18:52
I satisfied my curiosity with modules when I played around with embedded grub.cfg.
Its complex matter I found out.
Will see if it works, the iso is almost finished, but I suspect the script is very intolerant of formatting errors and stuff.

**Comment by philmmanjaro** [comment] 2017-03-27 19:02
Most likely not: https://github.com/manjaro/grub-theme/commit/01e3a9ee6bf0109f76352a90aa3c3650794424f9 And why is **grub-live-theme** in **rootfs** and not **livefs**?

**Comment by udeved** [comment] 2017-03-27 20:46
I got a workingversion now, but it atm only handles nonfree=true/false.
Some fine tuning left and I'll push it.

**Comment by philmmanjaro** [comment] 2017-03-27 21:15
Hmm, I've a kinda working version, however I'm not able to get it into a submenu: https://github.com/manjaro/grub-theme/commit/b3854fdc654229c81c5ab50ea356caade540dcc8

**Comment by udeved** [comment] 2017-03-27 21:16
Don't worry, I got working version with submenu, just need to set proper titles and defaults.

**Comment by udeved** [comment] 2017-03-27 21:17
@philmmanjaro 

Can you revert? I have uncommitted changes, and it would kick out your stuff.

**Comment by udeved** [comment] 2017-03-27 21:24
https://postimg.org/gallery/1sp3nb524/

**Comment by philmmanjaro** [comment] 2017-03-27 21:45
No Problem. I've created a [new branch](https://github.com/manjaro/grub-theme/commits/mhwd_cfg).

* set default to **free**
* more logical menu titels
* more logica menu placement

![menu-driver-1](https://cloud.githubusercontent.com/assets/5050022/24379405/395f7a22-1347-11e7-8410-cdab6f6d0ae0.png)

![menu-driver-2](https://cloud.githubusercontent.com/assets/5050022/24379414/3e6eacc2-1347-11e7-9ce5-e0a9f5c239a9.png)

![menu-driver-3](https://cloud.githubusercontent.com/assets/5050022/24379420/46306cf2-1347-11e7-8ad1-9f47433e62b7.png)

**Comment by philmmanjaro** [comment] 2017-03-28 05:36
Maybe somebody comes up with something better :smile: 

![manjaro-theme](https://cloud.githubusercontent.com/assets/5050022/24390455/4f26b90a-1389-11e7-8945-7ca1833bf56c.png)

**Comment by udeved** [comment] 2017-03-28 14:48
I think latest master is good start, it works and doesn't crash on hitting escape like in the other branch, where a menuentry is missing for the submenu.

**Comment by jonathonf** [comment] 2017-03-29 20:20
So I like the background, but the text is too glossy and the embossed logo don't fit with the flat/Material background; logo style from the User Guide cover would work fine.

WRT menu entries, is it possible to change the abbreviations (tz, lang, etc.) to a full word without breaking anything? For experience users 'tz' is fine, but it's easier for most people to understand e.g. "Time zone", "Language", "Keyboard layout", "Graphics driver".

**Comment by Huluti** [comment] 2017-03-29 20:26
Totally agree. It is not our official logo. We have to stop to use logos like these and have a real guideline.

**Comment by Ste74** [comment] 2017-03-29 20:56
@jonathonf , @Huluti ... the artwork of @philmmanjaro is only a draft 😉 : you can see here the discussion
[here](https://forum.manjaro.org/t/we-need-your-help/20342)

**Comment by Huluti** [comment] 2017-03-29 21:00
I see. So, it's good. 😉

**Comment by udeved** [comment] 2017-03-29 22:31
@philmmanjaro 

Grub theme has now sufficient driver selection.

One thing I noticed, and I am not sure if its by design or bug, the defaults are displayed, but not set.
you need to set everything to add params. It works same on siduction.

**Comment by oberon2007** [comment] 2017-03-29 23:00
Yes, that's bad. I noticed that too. The problem is that user doesn't realise he should select something. i3 has real problems when locale is not set.

**Comment by philmmanjaro** [comment] 2017-03-30 06:14
Seems this function does not work:

```
function locale_defaults {
    if [ -z "${def_bootlang}" ]; then
        def_bootlang="en_US"
        def_keyboard="us"
        def_timezone="UTC"
        def_drv="free"
    fi
}
```

**Comment by philmmanjaro** [comment] 2017-03-30 06:34
Well, seems to be by design. If you simply select help it will display a Warning.

**Comment by philmmanjaro** [comment] 2017-03-30 06:49
Fallback should fix this: https://github.com/manjaro/manjaro-tools-livecd/commit/f92c5910c9aae0780efaace7e1aa744d3d107005

**Comment by philmmanjaro** [comment] 2017-03-30 07:39
Current theme looks now like this:

![grub-menu](https://cloud.githubusercontent.com/assets/5050022/24492759/c287b350-152c-11e7-86d8-2699e636f5e1.png)

**Comment by udeved** [comment] 2017-03-30 08:17
https://github.com/manjaro/grub-theme/commit/6294cd035fc7577a73eec32b39332aa5dcae7305

This sets default parameters in kernelline.
Will improve later the day.

**Comment by udeved** [comment] 2017-03-30 15:03
We got all features we need completed.

@philmmanjaro 

I had disabled the fall back in live to see if everything grub works.
Technically, we don't need them any longer, but they don't hurt either.

Have you rebuilt live packages after your commit?

**Comment by oberon2007** [comment] 2017-03-30 15:10
live-base pkg was updated in unstable and testing, yes!

**Comment by udeved** [comment] 2017-03-30 15:13
Good, I have updated grub-theme. Please build iso if time allows for possible last minute changes in buildiso before 0.15.2 release. Works fine on my side, just need to update openrc specific stuff in profile before we rebuild packages.

**Comment by philmmanjaro** [comment] 2017-03-30 20:35
So after all fixed we can move the whole bunch to our **stable** branch after all?

**Comment by oberon2007** [comment] 2017-03-31 08:21
All looking good on i3 systemd on unstable. locale fallback is working, too :+1: Thank you!

**Comment by Strit** [comment] 2017-03-31 09:53
Does this mean that when I create an ISO when the new Manjaro-Tools get into stable, that it will use Grub for booting the ISO? Or do I need to change something in the profile for it?

**Comment by udeved** [comment] 2017-03-31 17:05
@philmmanjaro 

good to go now, I split the theme package, a common package depend with cfg file for the pure theme packages, so sonar or whatever else is covered.

@Strit 
Nope. :)

**Comment by Ste74** [comment] 2017-03-31 17:22
Well i have now started a gnome build ... ;)

**Comment by philmmanjaro** [comment] 2017-03-31 18:21
Ok, will test it over the weekend. Maybe another rc1 rebuild is needed :smile:

**Comment by Ste74** [comment] 2017-03-31 20:10
Tada 😄 gnome and new grub-theme is ok 😉 lang selection , keyboard selection and all 👍

**Comment by philmmanjaro** [comment] 2017-03-31 20:17
Excelent. Will test it myself soon. Currently building some kernels.

**Comment by philmmanjaro** [comment] 2017-04-01 10:21
I've rebuild our [rc1 build](https://sourceforge.net/projects/manjarotest/files/xfce/17.0.1-rc1/) and all seems fine. @Ste74, @oberon2007, @udeved: I think we are ready to release **v17.0.1** to our stable branch. Or did we still miss some important?

**Comment by oberon2007** [comment] 2017-04-02 15:28
I just installed from a freshly built i3 ISO, using calamares. Then I rebooted and on grub screen selected the 2nd entry "From Stick/HDD", but it boots again from the ISO!

**Comment by udeved** [comment] 2017-04-02 15:31
The grub live theme is not meant to be installed on the target install root!

**Comment by oberon2007** [comment] 2017-04-02 15:34
Well when you reboot without removing the ISO you end up there! And it has two entries to boot one or the other...

**Comment by oberon2007** [comment] 2017-04-02 15:38
If booting the HD from doesn't work, at least the not working entry should be removed.

**Comment by ThanosApostolou** [comment] 2017-04-02 15:55
I can confirm this too. I just tried it with my latest LXDE build on a previous LXDE installation on virtualbox. Choosing to boot from Stick/HDD is the same with booting from CD/DVD/ISO. If I choose "Installed BIOS System on hd0,msdos1"  then the system hangs and does nothing.

**Comment by philmmanjaro** [comment] 2017-04-02 16:01
**CD/DVD/ISO** and **Stick/HDD** and booting an installed system seems to be broken. I've to check which settings actual work. With **isolinux** we had a similar issue.

**Comment by philmmanjaro** [comment] 2017-04-02 16:36
Hmm, however we might need to drop unused code from us to make it more simple. This we should target for **v17.0.2** or so.

**Comment by udeved** [comment] 2017-04-02 16:38
We would have to make similar settings, perhaps simply add these in manjaro-tools-livecd repo, ad new package in livefs.

**Comment by oberon2007** [comment] 2017-04-02 16:48
I didn't look at the code of this at all, yet ... But, would it be non-trivial to just remove the second entry for now?

**Comment by udeved** [comment] 2017-04-02 16:50
https://github.com/manjaro/manjaro-tools-livecd/commit/89e0e9c79d2c2c7e95e69b2736fbe0905acdc285

**Comment by udeved** [comment] 2017-04-02 16:56
Above commit should basically activate usb efi detection I think.
Need to do a package now and will put it in unstable

**Comment by philmmanjaro** [comment] 2017-04-02 17:25
I think we are talking two different things here.

* we have two options to boot from our install media: **CD/DVD/ISO** and **Stick/HDD**. For Manjaro we only use one entry as the grub argument **fromhdd** we never use
* also, when you reboot your system after Manjaro got installed you may have an entry like `Installed BIOS System on hd0,msdos1` which doesn't work at all.

How we integrate **manjaro-live-portable-efi** and how it may help, I don't know yet ...

**Comment by udeved** [comment] 2017-04-02 17:27
But the portable efi package provides settings for usb/hdd efi, and set different efi path.
The reboot would make usb efi boot work I think.

**Comment by udeved** [comment] 2017-04-02 17:30
I got a bios setup in vbox.
Simple layout.
sda1 /boot
sda2 swap
sda3 /

It detects hd0,msdos3

It may get confused if /boot partition is not separate, which us unfortunately default in calamares.
We need to check.

**Comment by philmmanjaro** [comment] 2017-04-02 17:30
Maybe, we have to check this in our development cycle of **v17.0.2**. Currently some of our users have issues with the new **mesa-stack** and therefore **v17.0.1** got released now.

**Comment by ThanosApostolou** [comment] 2017-04-05 15:24
Hi, I'm not sure if it's relevant to the new grub theme/entries but I cannot boot into a 32bit ISO. The entry shows "NO SUITABLE KERNELS AVAILABLE" and after I choose it, it shows this: http://imgur.com/a/CcgnP. I tested it on my 32bit laptop and in virtualbox by choosing a 32bit drive. The thing is that if I choose 64bit drive in virtualbox, then it boots fine and command `uname -a` returns i686 kernel. I build my lxde ISO with command `buildiso -p lxde -b unstable -a i686 -r /home/thanos/build -t /home/thanos/build` so it's 100% i686 ISO, but for some reason it cannot boot on i686 systems.

**Comment by oberon2007** [comment] 2017-04-05 15:48
https://forum.manjaro.org/t/problem-with-manjaro-tools/21038/94

**Comment by Ste74** [comment] 2017-04-05 16:43
We have to decide very quickly if drop i686

**Comment by philmmanjaro** [comment] 2017-04-05 17:01
It has nothing to do with dropping **i686**. Nobody tested the grub menu as it is on **i686** thru and thru.

Somehow this code got activated after **cpuid -l** failed:

```
if [ "${havekernel}" != "Y" ]; then
    menuentry --class=find.none "NO SUITABLE KERNELS AVAILABLE" {echo $@  echo "There are no kernels suitable for this machine available."
        echo ""
        if ! cpuid -l; then
            echo "This machine is NOT 64bit capable."
            for kk in /boot/vmlinu*-*86; do
            if [ "$kk" != "/boot/vmlinu*-*86" ]; then
                have32="true"
            fi
            done
            if [ "${have32}" != "true" ]; then
            echo "There are no 32bit kernels available"
            echo "It appears you are trying to boot a 64bit release on a 32bit machine"
            echo "This cannot work!"
            fi
        fi
        echo "Press Escape to return to the main menu"
        sleep --interruptible 9999
        menu_reload
    }
fi
```
I think that line is wrong: `if [ "$kk" != "/boot/vmlinu*-*86" ]; then`

**Comment by philmmanjaro** [comment] 2017-04-05 17:05
With `cpuid -l` enabled we simply disable our 32bit ISOs to be bootable on a 32bit only CPU system. This is wrong from my point of view.

**Comment by Ste74** [comment] 2017-04-05 17:17
My intervent is more general not related at this .. and you are right we have missed to test the 32 bit version :\

**Comment by Huluti** [comment] 2017-04-05 18:17
If 32-bits are broken, let's remove at least temporarily.

**Comment by philmmanjaro** [comment] 2017-04-05 18:23
I've fixed the issue and re-uploading my ISOs: https://github.com/manjaro/grub-theme/commit/d0d9174edf63390252c3b33dc6db9504c4fa934c Issue was only on pure 32bit CPUs.

**Comment by Huluti** [comment] 2017-04-05 18:25
Nice!

**Comment by philmmanjaro** [comment] 2017-04-05 18:54
... seems I broke now **x86_64** bit ;) Tilt ...

**Comment by excalibur1234** [comment] 2017-04-05 19:14
i have recently built a manjaro ISO with this new grub theme.

i had a hard time (well, like 30s) figuring out how to boot manjaro. could the "boot manjaro.iso" option be placed on top (or marked by default)?
this would make it easier for users, who simply want to boot manjaro: they could simply wait or press ENTER.

it is not necessary to hurry this for 17.0.2, but if you find my idea useful, i would like to see it for 17.1 or 17.2.

**Comment by philmmanjaro** [comment] 2017-04-05 20:34
Seems I found a way to make it work. @excalibur1234 The current menu is logical. We even have now an icon to indicate which entry should be used. By default we pre-select the **language** so the user can easily select his locales with one selection. If all is set, simply select the **Boot:** option.

![grub-live-v2](https://cloud.githubusercontent.com/assets/5050022/24725668/108a1c6e-1a50-11e7-8df7-a9c430351fca.jpg)

**Comment by excalibur1234** [comment] 2017-04-05 21:23
i still think that "BOOT: Manjaro..." should be pre-selected.
but i do not mind, if you want to pre-select "lang". how about doing a release and then doing a poll what users want to have pre-selected? 

also, i feel that 
- "tz", should be called "time zone" (why do we need a time zone setting in live systems?)
- "keytable" should be called "keyboard layout" (or something similar)
- "lang" should be called "system language"
- "driver" should be called "video card driver"
- choices for "driver" are still not intuitive for beginners. "open source" and "proprietary" are probably more intuitive. but i am using manjaro for a long time and already know all that stuff. we should ask new users about that.
- the "reboot" option has no icon.
- selecting the "installed BIOS-system on hd0, msdos1" option and pressing ENTER breaks the grub boot screen (at least this was the case a coupe of days ago). if this is already fixed, ignore it.

imho, another problem for usability (at least this was the case a coupe of days ago):
1. select "tz"
2. press ENTER
3. change time zone or not and press ENTER
4. now, "lang" is selected
it would be intuitive, if "tz" was selected in step 4. i can understand, if there is no fix for this problem.

**Comment by fhdk** [comment] 2017-04-16 11:22
I really - really like this bootmenu and there is some merit to make the Boot option - more prominent.

One user got a bit upset - https://forum.manjaro.org/t/i-dont-understand-how-to-install/21633

I can see why you have chosen the order you have

* What time is it
* What is your alphabet
* What is your language
* Which graphics card do you have
* Boot

But I would probably ask 

* What is your language
* Which keyboard do you have
* Which graphics card do you have
* **Boot**

I wouldn't bother about timezone since Calamares does that from the country selection.

That was my € on the subject :laughing:

**Comment by startas** [comment] 2017-04-18 10:02
I just cant not notice that retarded line "driver=free", like if there ever were paid drivers. Also, driver for what ? This ancient, incorrect terminology must die and new, correct menu entry should be added, like "gpu drivers", "network drivers" or "floppy disk drivers", whatever you meant by "driver", and a version must be we choose from, not "free". Like, optimus graphics, nvidia only, intel only, amd only and so on.

**Comment by fhdk** [comment] 2017-04-18 10:55
@startas 
>And the last, why i can select empty lines ?
I tried - my keyboard melted :laughing: :

**Comment by udeved** [comment] 2017-04-18 11:58
I just cant not notice that retarded line "driver=free", like if there ever were paid drivers.

Its common linux terminology for non proprietary stuff, for retards.

**Comment by oberon2007** [comment] 2017-04-23 09:23
More serious issues that still need addressing I think are
* the 2nd boot entry, supposedly to boot from hdd that actually boots the ISO just like the first one
and
* an "installed system" entry that leads to a hang on a black screen when selected ...
 
![bootscreen](https://cloud.githubusercontent.com/assets/11800714/25312332/edfc1bc8-2816-11e7-9999-b2d8ac6ab379.png)

**Comment by philmmanjaro** [comment] 2017-05-12 09:04
We might take a look at SUSE once more.

![st-grub](https://cloud.githubusercontent.com/assets/5050022/25991010/1950cfcc-3702-11e7-995f-2a0458c18137.jpg)

They have it much more simplified as we have it now. Sure, our extra options to select the graphical driver, do a memtest or select locale and keyboard layout including timezone makes sense. I prefer to create an option menu for those and keep the basic boot options simple. Also we only need one Boot-Option for Manjaro itself.

Maybe we take a look to some other distros as well to see how they configure Grub2.

**Comment by udeved** [comment] 2017-05-12 09:06
We still haven't used to new usb live package. I think the usb boot option only works with this package installed.

**Comment by philmmanjaro** [comment] 2017-05-12 09:19
@udeved: yes, it is still the first design you made. I simply had no time yet to investigate. Therefore I created a [forums thread](https://forum.manjaro.org/t/grub2-iso-boot-menu-design/23516) in the hope somebody might take on this task. There are a lot [themes](https://www.gnome-look.org/browse/cat/109/ord/latest/) out there ...

**Comment by fhdk** [comment] 2017-05-12 16:43
I can take the challenge. What time frame are we talking about?

**Comment by philmmanjaro** [comment] 2017-05-12 16:45
@fhdk: we have no timeframes. Take the time needed and present us with some previews. Also we can't make everybody happy.

**Comment by philmmanjaro** [comment] 2017-05-30 07:09
At least we should remove the double entry we don't need on **Manjaro** to boot it.

**Comment by Huluti** [comment] 2017-12-09 18:11
Is it still open?

**Comment by codesardine** [comment] 2017-12-10 16:58
In my opinion Less is More. 

I would propose 3 boot options for Live ISO:
Manjaro Live
Boot from HDD
Advanced Options -  all other options go in here

Boot screen for installed systems: 
Manjaro XFCE
Windows 10
Advanced Options - all other options go in here

As a theme this is a good example of good design and simplicity, change colors to match Manjaro, remove blue square for example.

![687474703a2f2f692e696d6775722e636f6d2f7951434f6a6e522e706e67](https://user-images.githubusercontent.com/4250006/33807202-df5ed578-ddca-11e7-9ab0-1d2b17dcaf88.png)

**Comment by Ste74** [comment] 2017-12-10 17:09
Funny , from legendary bibo i have build in the past a grub theme for manjaro called `manj-grub` .. check it what you think ..

**Comment by codesardine** [comment] 2017-12-10 17:11
Can you link to it?

**Comment by Ste74** [comment] 2017-12-10 17:15
is in our repo and the src here
https://github.com/Ste74/manj-grub

**Comment by codesardine** [comment] 2017-12-10 17:19
The interface looks a bit busy, but is a 2year old concept

**Comment by Ste74** [comment] 2017-12-10 17:27
All grub 2 theme are old .. no new interface build in this year ;) all theme are only a remake of one.. yours is equal at an remake pclinuxos grub2 theme 
https://www.youtube.com/watch?v=pSO2s6znS5E :p 
Where is the source of your grub theme.. i can look into it ;)

**Comment by codesardine** [comment] 2017-12-10 17:31
This is just a theme i found randomly on google, did not try it myself.

https://github.com/LegendaryBibo/Steam-Big-Picture-Grub-Theme

**Comment by Ste74** [comment] 2017-12-17 21:54
Well this is my experimet with grub-live.. i have to move the menù on the left but do you think ? @philmmanjaro @oberon2007 
![grub1](https://user-images.githubusercontent.com/11218234/34084218-145d5044-e37d-11e7-95f9-4ec344d1b1dd.png)

**Comment by Ste74** [comment] 2017-12-23 14:27
@philmmanjaro @oberon2007 .. `grub-theme-dev ` for live system now ..
Please if you want test in your hands to see the effect ( only visual changes no grub code touch ) .
![virtualbox_mate_23_12_2017_15_22_45](https://user-images.githubusercontent.com/11218234/34320238-5ad84e12-e7f5-11e7-8702-c706403be688.png)

**Comment by philmmanjaro** [comment] 2017-12-23 14:50
We still have to work on the fonts. Looks not sharp. Already included in **v17.1-rc2**.

**Comment by Ste74** [comment] 2017-12-23 14:59
It use dejavu_sans font .. i can search other fonts in pf2 format .. i'm at work to include also a progress bar to countdown and autostartup
https://github.com/Ste74/grub-theme-dev/tree/master/manjaro-live

**Comment by philmmanjaro** [comment] 2017-12-23 16:14
I don't know on how the fonts get applied to **grub**.

**Comment by Ste74** [comment] 2017-12-23 16:28
Use a compressed file format called pf2.. We can compress in this format the normal ttf font..

**Comment by Chrysostomus** [comment] 2017-12-24 05:34
I don't think grub can do antialiasing, do if we want sharp fonts, maybe a bitmap font would be the right choice?

**Comment by codesardine** [comment] 2017-12-24 09:13
HI @Ste74  

It does look good, but i believe there is space for improvement.

In my opinion I would align the black box with welcome to manjaro and ditch the red color is hard to read and causes strain in the eye.

in the instructions area, were it says (boot select Os) maybe a bigger bold font, not too big, as it is hard to read.

Here is a link that helped me if you fancy reading it.
https://medium.com/@erikdkennedy/7-rules-for-creating-gorgeous-ui-part-1-559d4e805cda

**Comment by philmmanjaro** [comment] 2017-12-26 13:42
Fonts still look a little odd to me. Maybe it is just me ...

**Comment by Ste74** [comment] 2017-12-26 15:11
I have to try with terminus font.. Anyway to create the right font format for grub2 is present a tool provided by grub itself, just type man grub-mkfont

**Comment by Chrysostomus** [comment] 2018-01-10 15:37
I think terminus font would be good

**Comment by Chrysostomus** [comment] 2018-01-10 16:19
Tested now on installed system. It looks really nice with terminus!

However, I noticed an issue: The font gets smaller on selected menuitems. This makes text look jumpy when browsing menuentries. I think we need to keep the same font for both selected an deselected menuentries.

I think we could also use this on installed systems, sans the "Welcome to Manjaro" part.

**Comment by Chrysostomus** [comment] 2018-01-10 18:28
Okay, it still needs some work, because the text still jumps a bit when moving selection...

**Comment by Ste74** [comment] 2018-01-10 20:19
Yep.. is not perfect .. feel free to do PR .. i have to clean the unused code..
https://github.com/Ste74/grub-theme-dev

**Comment by Chrysostomus** [comment] 2018-01-12 06:35
![grubtheme](https://user-images.githubusercontent.com/12002226/34862430-0276c20c-f773-11e7-97c9-72c8e8ce7750.png)

I now got the fonts working properly, pr sent. I had to cut the rounded corners from the selection indicator, but now it works without text jumping about. Terminus font looks sharp and clean. I'm now using it also on my installed system. I think we could maybe make it the default grub theme also for installed systems. In that case we could look into adding automatically generated icons for different boot entries on multiboot systems.

Should we also do branding for refind?

**Comment by codesardine** [comment] 2018-01-12 09:36
It looks much better,  suggestion: maybe make letters bold in the bottom.

**Comment by Ste74** [comment] 2018-01-12 11:39
@Chrysostomus 👍 good .. Already merged your pr .. If you need other icons here you go only need to adjust manjaro-logo.. not sure is a square logo :p .. I like also the idea to do for installed system.. Only one thing: in the forum randomly see report of users whic not display properly the grub because the resolution is wrong .. maybe we have to look also into it ? 
For installed system we can make a grub-dev pkg to see before merge ?

**Comment by Chrysostomus** [comment] 2018-01-12 14:41
I got the icons working, sending a pr soon.

We should probably do something about the resolution, not sure what is the issue and how to help.

**Comment by Ste74** [comment] 2018-01-12 17:46
Now start a rebuild of grub-theme-live development to use in the mate and budge rc3/rc2 .. I have see this problem of resulution in the forum but don't remember when and how re found the post; we can ask at gohlip in PM it remember or how help us .. Whit grub is a master

**Comment by philmmanjaro** [comment] 2018-01-12 18:59
Excellent work guys :+1:

**Comment by Chrysostomus** [comment] 2018-01-13 21:55
Pull request now sent for adding icons. After that, when using the theme on installed system, it should automatically show distro icons for most common distors + windows/mac

**Comment by Ste74** [comment] 2018-01-14 17:14
Added the pkg theme for installed system : 
https://github.com/manjaro/packages-extra/commit/664d74c96fe3aea944c9c4f6c01340ef841d4800
build an iso to test if present aconflict somewhere and of course if work

**Comment by Ste74** [comment] 2018-01-14 18:21
Installed system in vbox via new pkg ...
![grub-installed](https://user-images.githubusercontent.com/11218234/34919219-f4a360e2-f95f-11e7-8bb8-02f64eb535bf.png)

Probably resolution on vbox show wrong position for welcome (?) but is great ..

**Comment by Strit** [comment] 2018-01-14 19:13
This looks very very nice. Is this a grub theme, that can be installed by a package soon?

**Comment by codesardine** [comment] 2018-01-14 19:27
It looks great.

By the way I found this to preview grub themes

https://github.com/hartwork/grub2-theme-preview

**Comment by Chrysostomus** [comment] 2018-01-14 19:29
Yep, that's what I used. 

@Strit That's the plan. I'm suggesting we could enable it by default in manjaro editions.

**Comment by Ste74** [comment] 2018-01-14 19:42
The pkg is grub-theme-manjaro-dev.. Is in unstable and auto install the theme after install. Only reboot and try..

**Comment by Ste74** [comment] 2018-01-14 19:49
Lol i have to correct the msg for the User to advice what is the theme name lol forgot to change the name of the theme

**Comment by oberon2007** [comment] 2018-01-19 18:52
To be honest I'm not totally convinced about the "Welcome to Manjaro" in that place. After all the grub screen isn't just for Manjaro when there are multiple boot entries... Not sure if we should just hijack this completely.
Also in general it looks like a bit too much in your face for my taste.
What's the deal with font size / resolution?
In Stefano's screenshot the font is very big and pixelated and the windows line gets cut off ...

**Comment by Ste74** [comment] 2018-01-19 19:03
The real look is in the @Chrysostomus screenshot .. the ugly look in my screenshot is because in vbox grub in general not respect the resolution of the OS ... for the Welcome is a word here
https://github.com/Ste74/grub-theme-dev/blob/master/manjaro-live/theme.txt#L20
so in installed system we can remove vith a sed command ..
Install it to see in real system the difference .. :\

**Comment by Chrysostomus** [comment] 2018-01-23 12:38
The look is a bit better than in my screenshot, because that too is virtualized environment with reduced resolution. 

I agree that "Welcome to manjaro" is not appropriate. For live environment yes, for installed system not to much. I think we don't need any text for the installed system.

**Comment by Ste74** [comment] 2018-01-23 17:58
For installed https://github.com/manjaro/packages-extra/commit/3f6422fd2ff33501900f0713b0eec3b7dbf04bd1
😉

**Comment by Chrysostomus** [comment] 2018-01-23 20:02
Btw, is the name of the package going to remain stable, or are we going to drop the -dev suffix at so point? And when shall it be available in stable? I'd like to implement support in manjaro-architect, but I would prefer to do it just once.

**Comment by Ste74** [comment] 2018-01-24 18:14
I do not understand what you mean .. `grub-theme-manjaro-dev` is already in stable ... yes if @philmmanjaro or @ oberon2007 agree to remove the suffix -dev we can create a PR and rebuild `grub-theme-manjaro` .. At the end we have only to decide if modify manjaro-tools and manjaro-architect to set the theme or simply leave how work now i.e. we set the theme with the package without touch the manajro-tools src and add grub-theme-manjaro into the packages list ..

**Comment by Chrysostomus** [comment] 2018-01-24 18:45
Manjaro-architect needs separate support, because it filters out grub packages from package-lists. This because user can choose from selection of bootloaders.

**Comment by Ste74** [comment] 2018-01-27 18:23
@Chrysostomus, now sync master with dev 😉 
https://github.com/manjaro/packages-extra/commit/1bc60456f6b5602f74509129f423ec45938cdb8c

**Comment by Chrysostomus** [comment] 2018-01-27 20:54
Thanks for the heads up! I'll be implementing it in git during the next week, situation permitting.

**Comment by Chrysostomus** [comment] 2018-01-29 22:36
Manjaro-architect now enables manjaro theme for both grub and refind.

**Closed** 2018-03-25 07:39 UTC
Labels: todo
