### ISSUE TITLE
lightdm fails on i3-ISO - i686 only!

### ISSUE THREAD

**Issue by oberon2007** [manjaro/release-plan#161] opened 2017-06-20 19:21 UTC
Built with mt-git master branch against stable today:
64bit version works fine. 32bit stops at

![i3_i686](https://user-images.githubusercontent.com/11800714/27351427-9c972560-55fd-11e7-9e98-c25104ad7826.png)

lightdm.log:

![i3_i686_2](https://user-images.githubusercontent.com/11800714/27351476-cb25c24c-55fd-11e7-837f-cf1d2d900f24.png)

![i3_i686_3](https://user-images.githubusercontent.com/11800714/27351539-05b3505a-55fe-11e7-98f3-46f599eec0f4.png)

![i3_i686_4](https://user-images.githubusercontent.com/11800714/27351606-3695e282-55fe-11e7-8489-78f0cd54e545.png)

@ThanosApostolou, I remember you had the exact same issue recently - can't find where this was posted... in the Forum, maybe?

**Comment by ThanosApostolou** [comment] 2017-06-20 19:29
It's here: https://github.com/manjaro/release-plan/issues/153

Philm said that this happens only on virtualbox now, but it works normally on Gnome Boxes. Unfortunately I am on my university's exams period, so I don't have time to do any tests myself until the weekend.

**Comment by oberon2007** [comment] 2017-06-20 19:33
It looks different to me. The other issue had kernel panic. But I remember you posting about the lightdm thing, too.

**Comment by ThanosApostolou** [comment] 2017-06-20 19:38
My lightdm problem back then, it was caused by mhwd which didn't find some drivers during boot, but it was fixed by @philmmanjaro who added some packages needed by mhwd (I believe this is the commit: https://github.com/manjaro/iso-profiles/commit/9ca4c8adf1f72df77b77466305acbe4f9b1b51cf).

Philm says that the kernel panic issue is now fixed with the latest **mkinitcpio-busybox** (see comment here: https://forum.manjaro.org/t/how-we-broke-i686-with-glibc/25925/3) but If you see the 2 latest comments in the above issue, philm says there's problem with lightdm now on i686 ISOs.

**Comment by oberon2007** [comment] 2017-06-20 19:45
Thanks a lot, @ThanosApostolou ! :)

**Comment by philmmanjaro** [comment] 2017-06-21 06:18
@oberon2007: please test it on **Boxes** as **Virtualbox** don't like the current **i686** set. I can't start any **i686** on Virtualbox to graphical mode as of now.

**Comment by philmmanjaro** [comment] 2017-06-21 07:44
Well, we have this issue also with **x86_64** when we use **manjaro-tools-git** as I posted earlier: https://github.com/manjaro/release-plan/issues/145 So something is off with **VirtualBox** and **LightDM**. I'll test with **XFCE** and the current packages in **testing** branch, to see what I'll see on my end.

**Comment by oberon2007** [comment] 2017-06-21 07:57
64bit is fine for me.

**Comment by philmmanjaro** [comment] 2017-06-21 09:31
@oberon2007: **plymouth** ?!?. Do you still use it? We dropped that from our ISOs a while ago ...

**Comment by Ste74** [comment] 2017-06-21 10:40
I  bought a new laptop ( intel i5 7200 and nvidia gx card ) when finishing to transfer my Manjaro into it i can check my build ( before i built only x86_64 ) ..

**Comment by philmmanjaro** [comment] 2017-06-21 10:43
@Ste74: I already tested **XFCE**, **Gnome** and **KDE**. None of them boot in **VirtualBox** with **i686**. The **Gnome** edition doesn't boot at all in **Boxes**. Seems we should remove the "fix" for the double **gnome-shell** sessions. **gdm** needs the second **gnome-shell** to function properly. **Boxes** is a gnome tool and showcases that our "workaround" doesn't work.

**Comment by Ste74** [comment] 2017-06-21 10:48
I know boxes but never used it .. well so the question is leave or not the workaround for gdm ?

**Comment by philmmanjaro** [comment] 2017-06-21 11:20
Well, it doesn't login, so it must be something else. Needs more testing. Anyway, **i686** is general a mess right now ...

**Comment by philmmanjaro** [comment] 2017-06-21 13:28
Seems on **i686** it takes way to long to authenticate the user login. Try to login to TTY from any live-session. For **lightdm.service** I get this:

![lightdm-i686-v17 0 2-pre7](https://user-images.githubusercontent.com/5050022/27386377-ec0b1e6a-5695-11e7-9518-d638647ca117.jpg)

... and similar logs as you posted already. Maybe we should try **dbus-x11** once more.

**Comment by philmmanjaro** [comment] 2017-06-21 13:44
For XFCE it doesn't make a difference if **dbus** or **dbus-x11** was used. To login into a TTY you need more than 50s.

**Comment by philmmanjaro** [comment] 2017-06-21 15:16
Seems to be a similar issue with **OpenRC** and **i686**. **Virtualbox** is not able to boot the image, however it starts just fine on **Boxes** ...

**Comment by oberon2007** [comment] 2017-06-21 16:40
**vbox** has this: [1]

>    CredsWaitTimeout: Timeout (in seconds) to let pam_vbox wait for credentials to arrive. When no credentials arrive within this timeout, authentication of pam_vbox will be set to failed and the next PAM module in chain will be asked. If this property is not specified, set to "0" or an invalid value, an infinite timeout will be used. This property must be set read-only for the guest (RDONLYGUEST).

Not that it would be desirable to extend the timeout to a minute or so ... 😜 But I guess that explains why authentication fails in vbox...
Theoretically apparently there are ways to extend timeout from guest side anyway. 

[1] https://www.virtualbox.org/manual/ch09.html

**Comment by philmmanjaro** [comment] 2017-06-22 21:19
Add **xdriver=vesa** to your kernel cmd or [disable](https://github.com/manjaro/iso-profiles/commit/e8b7840a69a5963c5e5ab47e3ec9a94935830b94) **VirtualBox** drivers for i686. See also [here](https://github.com/manjaro/release-plan/issues/162).

**Closed by philmmanjaro** 2017-06-22 21:19 UTC
